version: '3.3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./:/app/server
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
