version: '3.3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80

  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    #    ports:
    #      - 3000:3000
    restart: on-failure
    volumes:
      - /app/node_modules
    container_name: client

  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    #    ports:
    #      - '3001:3001'
    environment:
      - PORT=3001
    env_file:
      - ./server/.env
    restart: on-failure
    container_name: server
