name: backend deploy CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: server

jobs:
  tests:
    name: Testing Backend
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Use Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
