name: backend deploy CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: server

env:
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

jobs:
  # # —— Run Tests on API-Server —————————————————————————————————————————————
  # tests:
  #   name: Testing Backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 14
  #     - run: npm ci
  #     - run: npm test
  # # —— Build Image and Push to Dockerhub —————————————————————————————————————————————
  # dockerhub:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: build and push server image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./server
  #         push: true
  #         tags: brianchungcs/blogger-app-server:latest

  #     - name: build and push client image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./client
  #         push: true
  #         tags: brianchungcs/blogger-app-client:latest

  #     - name: build and push nginx image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./nginx
  #         push: true
  #         tags: brianchungcs/blogger-app-nginx:latest
  # —— Deploy: Send Dockerrun.aws.json to Elastic Beanstalk —————————————————————————————————————————————
  elb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Generate deployment package
        run: cat ../Dockerrun.aws.json
        run: zip -r deploy.zip ../Dockerrun.aws.json -x '*.git*'
#        run: zip deploy.zip ../Dockerrun.aws.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: blogger-app
          environment_name: Bloggerapp-env
          version_label: 1
          region: us-west-1
          deployment_package: deploy.zip
