name: backend deploy CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Testing Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: blogger-app/server
          path: server
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test

  push_to_registry:
    name: Pushing to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: blogger-app/server
          path: server
          ref: master

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: brianchungcs/blogger-app
          tags: latest
          registry: https://index.docker.io/v2/
          dockerfile: server/Dockerfile
          directory: server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
